version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_library
    restart: always
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: django_library
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env            # ✅ LOAD environment variables into container
    volumes:
      - .:/app
    command: >
      bash -c "
      python manage.py migrate &&
      gunicorn Library_Management.wsgi:application --bind 0.0.0.0:8000"

volumes:
  db_data:
