name: CI Build, Test, Push, and Run Locally

on:
  push:
    branches:
      - main

jobs:
  build-test-push-run:
    runs-on: self-hosted  # ✅ Make sure your runner is connected and running

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: 📝 Generate .env from template
        run: |
          sed 's/{{ DB_HOST }}/host.docker.internal/' .env.template > .env

      - name: 🧱 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📦 Build & Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t devnotfound404/library-app:latest \
            . --push


      
      - name: 🚀 Deploy Locally with deploy.sh (Optional)
        if: runner.name == 'self-hosted'
        run: |
          chmod +x deploy.sh
          ./deploy.sh
